<a href="https://colab.research.google.com/github/bhoop70233/Data-Science/blob/main/01_fundamental.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [4]:
import numpy as np

# Generate a list of 4 lists of 5 random numbers each
list_of_lists = []
for i in range(4):
    # Generate a list of 5 numbers between 0 and 100 and add this list to [list_of_lists]
    list_of_lists.append(np.random.randint(low=0, high=100, size=5))

# Convert list_of_lists into numpy matrix
matrix = np.matrix(list_of_lists)
print("Here is your matrix:\n{}\n".format(matrix))

# Addition
new_matrix = np.add(matrix, 5)
print("Here is your matrix with addition +5:\n{}\n".format(new_matrix))

# Multiplication
new_matrix = np.multiply(matrix, matrix)
print("Here is your matrix multiplied by itself:\n{}\n".format(new_matrix))

# Transposition
new_matrix = np.transpose(matrix)
print("Here is your matrix transposed:\n{}\n".format(new_matrix))


Here is your matrix:
[[72 61 77 60 17]
 [82  3 31 55 41]
 [71 69 38  2 48]
 [67 98 24 31 66]]

Here is your matrix with addition +5:
[[ 77  66  82  65  22]
 [ 87   8  36  60  46]
 [ 76  74  43   7  53]
 [ 72 103  29  36  71]]

Here is your matrix multiplied by itself:
[[5184 3721 5929 3600  289]
 [6724    9  961 3025 1681]
 [5041 4761 1444    4 2304]
 [4489 9604  576  961 4356]]

Here is your matrix transposed:
[[72 82 71 67]
 [61  3 69 98]
 [77 31 38 24]
 [60 55  2 31]
 [17 41 48 66]]

