<a href="https://colab.research.google.com/github/bhoop70233/Data-Science/blob/main/NN_from_Scratch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
input=[1,2,3]
weights=[0.2,0.8,-0.5]
bias=2


In [2]:
output=(input[0]*weights[0]+input[1]*weights[1]+input[2]*weights[2]+bias)
print(output)

2.3


In [3]:
inputs=[1,2,3,2.5]
weights1=[0.2,0.8,-0.5,1]
weights2=[0.5,-0.91,0.34,-0.45]
weights3=[-0.56,-0.34,0.23,0.45]
bias1=2
bias2=3
bias3=0.5

outputs=[
    #Neuron 1:
    inputs[0]*weights1[0]+
    inputs[1]*weights1[1]+
    inputs[2]*weights1[2]+
    inputs[3]*weights1[3]+bias1,

    #Neurons 2:
    inputs[0]*weights2[0]+
    inputs[1]*weights2[1]+
    inputs[2]*weights2[2]+
    inputs[3]*weights2[3]+bias2,


    #Neuron 3:
    inputs[0]*weights3[0]+
    inputs[1]*weights3[1]+
    inputs[2]*weights3[2]+
    inputs[3]*weights3[3]+bias3

]
print(outputs)

[4.8, 1.575, 1.0749999999999997]


In [4]:
inputs=[1,2,3,2.5]
weights=[[0.2,0.8,-0.5,1],
         [0.5,-0.91,0.26,-0.5],
         [-0.26,-0.27,0.17,0.87]]
biases=[2,3,0.6]

#Output of current layer
layer_outputs=[]
# For each neuron
for neuron_weights,neuron_bias in zip(weights,biases):
      # Zeroed output of given neuron
      neuron_output=0
      # For each input and weight to the neuron
      for n_input,weight in zip(inputs,neuron_weights):
        #Multiply this input by associated weight
        # and add to the neuron's output variable
        neuron_output+=n_input*weight
      #Add bias
      neuron_output+=neuron_bias
      #Put neuron's result to the layer's output list
      layer_outputs.append(neuron_output)
print(layer_outputs)

[4.8, 1.21, 2.485]


In [5]:
#simple list
l=[1,5,6,2]
#list of lists
lol=[[1,5,6,2],
     [3,2,1,3]]
#list of lists of lists
lolol=[[[1,5,6,2],
        [3,2,1,3]],
        [[5,2,1,2],
         [6,4,8,4]],
       [[2,8,5,3],
        [1,1,9,4]]]

In [6]:
another_list_of_lists=[[4,2,3],
                       [5,1]]

In [7]:
list_matrix_array=[[4,2],
                   [5,1],
                   [8,2]]

In [8]:
#dot product
a=[1,2,3]
b=[2,3,4]
dot_product=a[0]*b[0]+a[1]*b[1]+a[2]*b[2]
print(dot_product)


20


In [9]:
import numpy as np
input=[1.0,2.0,3.0,2.5]
weights=[0.2,0.8,-0.5,1.0]
bias=2.0
outputs=np.dot(weights,inputs)+bias
print(outputs)

4.8


In [10]:
import numpy as np
input=[1.0,2.0,3.0,2.5]
weights=[[0.2,0.8,-0.5,1],
         [0.5,-0.91,0.26,-0.5],
         [-0.26,-0.27,0.17,0.87]]
biases=[2.0,3.0,0.5]
layer_outputs=np.dot(weights,inputs)+biases
print(layer_outputs)

[4.8   1.21  2.385]


In [11]:
np.array([[1,2,3]])

array([[1, 2, 3]])

In [12]:
a=[1,2,3]
print(np.array([a]))

[[1 2 3]]


In [13]:
a=[1,2,3]
print(np.expand_dims(np.array(a),axis=0))

[[1 2 3]]


In [14]:
import numpy as np
a=[1,2,3]
b=[2,3,4]
a=np.array([a])
b=np.array([b]).T

print(np.dot(a,b))

[[20]]
